[package]
name = "net-info"
version = "0.1.0"
authors = ["b1tg"]
edition = "2018"
build = "build.rs"


[dependencies]
slint = "0.2.1"
cli-clipboard = "0.2.1"
[build-dependencies]
slint-build = "0.2.1"
